POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "matias@abc.fi",
    "password": "password"
}

#####
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "pekka123@pk.fi",
    "password": "password"
}